version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shake_art
      MYSQL_USER: shake_user
      MYSQL_PASSWORD: shake_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shake_art_network

volumes:
  mysql_data:

networks:
  shake_art_network: