CREATE TABLE IF NOT EXISTS `user` (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(191) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT uk_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS workshop (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(150) NOT NULL,
	description TEXT,
	starts_at DATETIME NOT NULL,
	ends_at DATETIME NOT NULL,
	capacity INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS registration (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT NOT NULL,
	workshop_id BIGINT NOT NULL,
	registered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_registration_user FOREIGN KEY (user_id) REFERENCES `user`(id) ON DELETE CASCADE,
	CONSTRAINT fk_registration_workshop FOREIGN KEY (workshop_id) REFERENCES workshop(id) ON DELETE CASCADE,
	CONSTRAINT uk_registration_user_workshop UNIQUE (user_id, workshop_id)
);
